# Generated by Django 2.2 on 2019-04-08 17:06

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('mobile', models.IntegerField()),
                ('courses', multiselectfield.db.fields.MultiSelectField(choices=[('python', 'python'), ('django', 'django'), ('ui', 'uitechonologies'), ('restapi', 'restapi'), ('flask', 'flask')], max_length=100)),
                ('locations', multiselectfield.db.fields.MultiSelectField(choices=[('hyd', 'hyderabad'), ('bang', 'banglore'), ('che', 'chennai')], max_length=100)),
                ('shifts', multiselectfield.db.fields.MultiSelectField(choices=[('mrng', 'morning'), ('aftrn', 'afternoon'), ('evng', 'evening'), ('nyt', 'night')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('date', models.DateField()),
                ('feedback', models.TextField(max_length=600)),
            ],
        ),
    ]
